USERNAME=$1
DIR_TO_TRANSFER=$2
DEST_HOST=$3
DEST_DIR=$4
ssh -l $USERNAME $DEST_HOST "mkdir -p $DEST_DIR"
echo "scp -r $DIR_TO_TRANSFER $USERNAME@$DEST_HOST:$DEST_DIR/" 
scp -r $DIR_TO_TRANSFER $USERNAME@$DEST_HOST:$DEST_DIR/
