ZK_HOME=$1
SERVER_JAVA_HOME=$2
shift 2
cd $MANAGIX_HOME/.installer/zookeeper
tar cf zk.pkg.tar *
zk_server_id=1
for zk_host in  $@
do
  ssh $zk_host "mkdir -p $ZK_HOME"
  scp ./zk.pkg.tar $zk_host:$ZK_HOME/
  ssh $zk_host "cd $ZK_HOME && tar xf $ZK_HOME/zk.pkg.tar && chmod +x $ZK_HOME/bin/start_zk.sh"
  ssh $zk_host "$ZK_HOME/bin/start_zk.sh $ZK_HOME $zk_server_id $SERVER_JAVA_HOME" &
  zk_server_id=`expr $zk_server_id + 1`	
done
