FROM ubuntu:22.04
RUN apt -y update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt -y install systemd openjdk-17-jre-headless unzip wget curl python3-pip python3-venv python3-systemd
RUN pip3 install shiv msgpack
COPY target/asterix-server_*all.deb .
RUN dpkg -i asterix-server*.deb
COPY src/test/resources/cc.conf /opt/apache-asterixdb/cc.conf
COPY src/test/resources/passwd /opt/apache-asterixdb/etc/passwd
RUN mkdir -p /etc/systemd/system/pyudf@.service.d/
COPY src/test/resources/testenv.conf /etc/systemd/system/pyudf@.service.d/
COPY src/test/resources/setup.sh /opt
RUN chmod +x /opt/setup.sh
RUN systemctl enable asterix-nc asterix-cc pyudf.socket

EXPOSE 19001 19002 19004

CMD [ "/lib/systemd/systemd" ]
