ssh asterix-master ./hivesterix/target/appassembler/asterix_dbg/stopcc.sh
ssh asterix-001 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-002 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-003 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-004 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-005 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-006 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-007 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-008 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-009 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
ssh asterix-010 ./hivesterix/target/appassembler/asterix_dbg/stopnc.sh
