#!/usr/bin/env bash
#/*
# Copyright 2009-2013 by The Regents of the University of California
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License from
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/
if [ -z $MANAGIX_HOME ]
 then
   pushd $(dirname $0) >/dev/null
   cd ..
   export MANAGIX_HOME=$(pwd)
   popd >/dev/null
fi

for jar in `ls $MANAGIX_HOME/lib/*.jar`
  do 
  if [ -z $MANAGIX_CLASSPATH ] 
  then 
    MANAGIX_CLASSPATH=$jar 
  else
    MANAGIX_CLASSPATH=$MANAGIX_CLASSPATH:$jar 
  fi
done

MANAGIX_CLASSPATH=$MANAGIX_CLASSPATH:$MANAGIX_HOME/conf/log4j.properties
java $JAVA_OPTS -Dlog4j.configuration=file:$MANAGIX_HOME/conf/log4j.properties -cp $MANAGIX_CLASSPATH org.apache.asterix.installer.driver.InstallerDriver $@
