/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * Generated by AI in Cursor IDE
 * Model: Claude Opus 4
 */
package org.apache.hyracks.storage.am.lsm.btree;

import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

import org.apache.hyracks.data.std.util.ArrayBackedValueStorage;
import org.apache.hyracks.dataflow.common.data.accessors.ITupleReference;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaEstimator;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaEstimator.ComponentStats;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaSampler;
import org.junit.Test;

/**
 * Comprehensive LSM Theta Sketch simulation tests.
 *
 * This test simulates a realistic LSM engine where:
 * - There are N LSM indexes, each with disjoint key ranges
 * - Each LSM index has multiple disk components (ThetaSamplers)
 * - Components within an LSM index can have overlapping keys (updates/upserts)
 * - Deletes (antimatter tuples) can occur in newer components
 *
 * Tests measure how error rate behaves with:
 * - Increasing duplicate/upsert percentage
 * - Increasing delete percentage
 * - Increasing number of LSM indexes (N from 1 to 128)
 */
public class LSMThetaSketchTest {

    private static final int[] KEY_FIELDS = { 0 };
    private static final Random RND = new Random(42);

    // ========================================================================
    // Mock Tuple Implementation
    // ========================================================================

    private static class MockTuple implements ITupleReference {
        private final byte[][] fields;

        public MockTuple(int value) {
            this.fields = new byte[1][];
            fields[0] = intToBytes(value);
        }

        private static byte[] intToBytes(int value) {
            return new byte[] { (byte) (value >> 24), (byte) (value >> 16), (byte) (value >> 8), (byte) value };
        }

        @Override
        public int getFieldCount() {
            return fields.length;
        }

        @Override
        public byte[] getFieldData(int fIdx) {
            return fields[fIdx];
        }

        @Override
        public int getFieldStart(int fIdx) {
            return 0;
        }

        @Override
        public int getFieldLength(int fIdx) {
            return fields[fIdx].length;
        }
    }

    private static class MockAntimatterTuple extends MockTuple
            implements org.apache.hyracks.storage.am.lsm.common.api.ILSMTreeTupleReference {
        public MockAntimatterTuple(int value) {
            super(value);
        }

        @Override
        public boolean isAntimatter() {
            return true;
        }

        @Override
        public int getTupleSize() {
            return getFieldLength(0);
        }

        @Override
        public void setFieldCount(int fieldCount) {
        }

        @Override
        public void setFieldCount(int fieldStartIndex, int fieldCount) {
        }

        @Override
        public void resetByTupleOffset(byte[] buf, int tupleStartOffset) {
        }

        @Override
        public void resetByTupleIndex(org.apache.hyracks.storage.am.common.api.ITreeIndexFrame frame, int tupleIndex) {
        }
    }

    // ========================================================================
    // LSM Index Simulation
    // ========================================================================

    /**
     * Represents a single LSM index with multiple disk components.
     */
    private static class LSMIndex {
        private final int keyRangeStart;
        private final int keyRangeEnd;
        private final List<ComponentStats> components = new ArrayList<>();
        private final Set<Integer> liveKeys = new HashSet<>();

        public LSMIndex(int indexId, int keyRangeStart, int keyRangeEnd) {
            this.keyRangeStart = keyRangeStart;
            this.keyRangeEnd = keyRangeEnd;
        }

        /**
         * Simulates a flush with the given parameters.
         *
         * @param keysToInsert      number of new keys to insert
         * @param upsertPercentage  percentage of existing keys to update (0-100)
         * @param deletePercentage  percentage of existing keys to delete (0-100)
         */
        public void flush(int keysToInsert, int upsertPercentage, int deletePercentage) throws IOException {
            ThetaSampler sampler = new ThetaSampler(KEY_FIELDS);
            Set<Integer> keysInThisFlush = new HashSet<>();

            // 1. Upsert existing keys (update them)
            if (!liveKeys.isEmpty() && upsertPercentage > 0) {
                int upsertCount = (int) (liveKeys.size() * upsertPercentage / 100.0);
                List<Integer> existingKeys = new ArrayList<>(liveKeys);
                for (int i = 0; i < upsertCount && i < existingKeys.size(); i++) {
                    int key = existingKeys.get(RND.nextInt(existingKeys.size()));
                    if (!keysInThisFlush.contains(key)) {
                        sampler.addTuple(new MockTuple(key));
                        keysInThisFlush.add(key);
                    }
                }
            }

            // 2. Delete some existing keys
            if (!liveKeys.isEmpty() && deletePercentage > 0) {
                int deleteCount = (int) (liveKeys.size() * deletePercentage / 100.0);
                List<Integer> existingKeys = new ArrayList<>(liveKeys);
                for (int i = 0; i < deleteCount && i < existingKeys.size(); i++) {
                    int key = existingKeys.get(RND.nextInt(existingKeys.size()));
                    if (!keysInThisFlush.contains(key)) {
                        sampler.addTuple(new MockAntimatterTuple(key));
                        keysInThisFlush.add(key);
                        liveKeys.remove(key);
                    }
                }
            }

            // 3. Insert new unique keys
            int inserted = 0;
            int nextKey = keyRangeStart;
            while (inserted < keysToInsert && nextKey <= keyRangeEnd) {
                if (!liveKeys.contains(nextKey) && !keysInThisFlush.contains(nextKey)) {
                    sampler.addTuple(new MockTuple(nextKey));
                    liveKeys.add(nextKey);
                    keysInThisFlush.add(nextKey);
                    inserted++;
                }
                nextKey++;
            }

            // If we ran out of range, try random keys in range
            while (inserted < keysToInsert) {
                int key = keyRangeStart + RND.nextInt(keyRangeEnd - keyRangeStart + 1);
                if (!liveKeys.contains(key) && !keysInThisFlush.contains(key)) {
                    sampler.addTuple(new MockTuple(key));
                    liveKeys.add(key);
                    keysInThisFlush.add(key);
                    inserted++;
                }
            }

            // Serialize and add to components (newest first)
            ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
            serialized.append(sampler.serialize());
            components.add(0, ThetaSampler.deserialize(serialized));
        }

        public long estimateCardinality() {
            return ThetaEstimator.estimateCardinality(components);
        }

        public int getActualLiveCount() {
            return liveKeys.size();
        }

        public int getComponentCount() {
            return components.size();
        }
    }

    // ========================================================================
    // Test: Error Rate vs Number of LSM Indexes (N)
    // ========================================================================

    @Test
    public void testErrorRateVsNumberOfIndexes() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Error Rate vs Number of LSM Indexes (N)");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 10,000 keys per index, 3 flushes per index, 0% upsert, 0% delete");
        System.out.println();

        int[] indexCounts = { 1, 2, 4, 8, 16, 32, 64, 128 };
        int keysPerIndex = 10000;
        int flushesPerIndex = 3;
        int keysPerFlush = keysPerIndex / flushesPerIndex;

        System.out.printf("%-10s %-15s %-15s %-15s %-15s%n", "N", "Expected", "Estimated", "Error %", "Components");
        System.out.println("-".repeat(70));

        for (int n : indexCounts) {
            List<LSMIndex> indexes = new ArrayList<>();
            long totalEstimated = 0;
            int totalActual = 0;
            int totalComponents = 0;

            // Create N LSM indexes with disjoint key ranges
            for (int i = 0; i < n; i++) {
                int rangeStart = i * keysPerIndex * 2;
                int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
                LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                // Perform flushes
                for (int f = 0; f < flushesPerIndex; f++) {
                    index.flush(keysPerFlush, 0, 0);
                }

                indexes.add(index);
                totalEstimated += index.estimateCardinality();
                totalActual += index.getActualLiveCount();
                totalComponents += index.getComponentCount();
            }

            double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
            System.out.printf("%-10d %-15d %-15d %-15.2f %-15d%n", n, totalActual, totalEstimated, errorRate,
                    totalComponents);
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Error Rate vs Upsert Percentage
    // ========================================================================

    @Test
    public void testErrorRateVsUpsertPercentage() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Error Rate vs Upsert Percentage");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 8 indexes, 20,000 keys per index, 5 flushes, 0% delete");
        System.out.println();

        int[] upsertPercentages = { 0, 10, 20, 30, 40, 50, 60, 70, 80, 90 };
        int numIndexes = 8;
        int keysPerIndex = 20000;
        int numFlushes = 5;
        int baseKeysPerFlush = keysPerIndex / numFlushes;

        System.out.printf("%-12s %-15s %-15s %-15s%n", "Upsert %", "Expected", "Estimated", "Error %");
        System.out.println("-".repeat(60));

        for (int upsertPct : upsertPercentages) {
            long totalEstimated = 0;
            int totalActual = 0;

            for (int i = 0; i < numIndexes; i++) {
                int rangeStart = i * keysPerIndex * 2;
                int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
                LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                // First flush: insert base keys
                index.flush(baseKeysPerFlush, 0, 0);

                // Subsequent flushes: upsert existing + new keys
                for (int f = 1; f < numFlushes; f++) {
                    index.flush(baseKeysPerFlush / 2, upsertPct, 0);
                }

                totalEstimated += index.estimateCardinality();
                totalActual += index.getActualLiveCount();
            }

            double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
            System.out.printf("%-12d %-15d %-15d %-15.2f%n", upsertPct, totalActual, totalEstimated, errorRate);
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Error Rate vs Delete Percentage
    // ========================================================================

    @Test
    public void testErrorRateVsDeletePercentage() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Error Rate vs Delete Percentage");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 8 indexes, 20,000 keys per index, 5 flushes, 0% upsert");
        System.out.println();

        int[] deletePercentages = { 0, 5, 10, 15, 20, 25, 30, 40, 50 };
        int numIndexes = 8;
        int keysPerIndex = 20000;
        int numFlushes = 5;
        int baseKeysPerFlush = keysPerIndex / numFlushes;

        System.out.printf("%-12s %-15s %-15s %-15s%n", "Delete %", "Expected", "Estimated", "Error %");
        System.out.println("-".repeat(60));

        for (int deletePct : deletePercentages) {
            long totalEstimated = 0;
            int totalActual = 0;

            for (int i = 0; i < numIndexes; i++) {
                int rangeStart = i * keysPerIndex * 2;
                int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
                LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                // First flush: insert base keys
                index.flush(baseKeysPerFlush, 0, 0);

                // Subsequent flushes: delete some + add new keys
                for (int f = 1; f < numFlushes; f++) {
                    index.flush(baseKeysPerFlush / 2, 0, deletePct);
                }

                totalEstimated += index.estimateCardinality();
                totalActual += index.getActualLiveCount();
            }

            double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
            System.out.printf("%-12d %-15d %-15d %-15.2f%n", deletePct, totalActual, totalEstimated, errorRate);
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Error Rate vs Combined Upsert + Delete
    // ========================================================================

    @Test
    public void testErrorRateVsCombinedUpsertDelete() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Error Rate vs Combined Upsert + Delete Percentage");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 16 indexes, 15,000 keys per index, 6 flushes");
        System.out.println();

        int[][] scenarios = {
                // {upsert%, delete%}
                { 0, 0 }, { 10, 5 }, { 20, 10 }, { 30, 15 }, { 40, 20 }, { 50, 25 }, { 60, 30 }, { 70, 35 },
                { 80, 40 } };

        int numIndexes = 16;
        int keysPerIndex = 15000;
        int numFlushes = 6;
        int baseKeysPerFlush = keysPerIndex / numFlushes;

        System.out.printf("%-10s %-10s %-15s %-15s %-15s%n", "Upsert %", "Delete %", "Expected", "Estimated",
                "Error %");
        System.out.println("-".repeat(70));

        for (int[] scenario : scenarios) {
            int upsertPct = scenario[0];
            int deletePct = scenario[1];

            long totalEstimated = 0;
            int totalActual = 0;

            for (int i = 0; i < numIndexes; i++) {
                int rangeStart = i * keysPerIndex * 2;
                int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
                LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                // First flush: insert base keys
                index.flush(baseKeysPerFlush, 0, 0);

                // Subsequent flushes: upsert + delete + new keys
                for (int f = 1; f < numFlushes; f++) {
                    index.flush(baseKeysPerFlush / 3, upsertPct, deletePct);
                }

                totalEstimated += index.estimateCardinality();
                totalActual += index.getActualLiveCount();
            }

            double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
            System.out.printf("%-10d %-10d %-15d %-15d %-15.2f%n", upsertPct, deletePct, totalActual, totalEstimated,
                    errorRate);
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Error Rate vs Number of Components per Index
    // ========================================================================

    @Test
    public void testErrorRateVsComponentCount() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Error Rate vs Number of Components per Index");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 8 indexes, 30,000 total keys per index, varying flush count");
        System.out.println();

        int[] flushCounts = { 1, 2, 3, 5, 10, 15, 20, 30 };
        int numIndexes = 8;
        int totalKeysPerIndex = 30000;

        System.out.printf("%-12s %-15s %-15s %-15s %-15s%n", "Flushes", "Keys/Flush", "Expected", "Estimated",
                "Error %");
        System.out.println("-".repeat(75));

        for (int numFlushes : flushCounts) {
            int keysPerFlush = totalKeysPerIndex / numFlushes;

            long totalEstimated = 0;
            int totalActual = 0;

            for (int i = 0; i < numIndexes; i++) {
                int rangeStart = i * totalKeysPerIndex * 2;
                int rangeEnd = rangeStart + totalKeysPerIndex * 2 - 1;
                LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                for (int f = 0; f < numFlushes; f++) {
                    index.flush(keysPerFlush, 10, 5); // Moderate upsert/delete
                }

                totalEstimated += index.estimateCardinality();
                totalActual += index.getActualLiveCount();
            }

            double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
            System.out.printf("%-12d %-15d %-15d %-15d %-15.2f%n", numFlushes, keysPerFlush, totalActual,
                    totalEstimated, errorRate);
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Full Matrix - N x Upsert% x Delete%
    // ========================================================================

    @Test
    public void testFullMatrix() throws IOException {
        System.out.println("=".repeat(100));
        System.out.println("TEST: Full Matrix - N Indexes x Upsert% x Delete%");
        System.out.println("=".repeat(100));
        System.out.println("Configuration: 5,000 keys per index, 4 flushes per index");
        System.out.println();

        int[] indexCounts = { 1, 4, 16, 64 };
        int[] upsertPcts = { 0, 25, 50 };
        int[] deletePcts = { 0, 10, 25 };
        int keysPerIndex = 5000;
        int numFlushes = 4;
        int keysPerFlush = keysPerIndex / numFlushes;

        System.out.printf("%-8s %-10s %-10s %-15s %-15s %-12s%n", "N", "Upsert %", "Delete %", "Expected", "Estimated",
                "Error %");
        System.out.println("-".repeat(80));

        for (int n : indexCounts) {
            for (int upsertPct : upsertPcts) {
                for (int deletePct : deletePcts) {
                    long totalEstimated = 0;
                    int totalActual = 0;

                    for (int i = 0; i < n; i++) {
                        int rangeStart = i * keysPerIndex * 2;
                        int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
                        LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

                        // First flush
                        index.flush(keysPerFlush, 0, 0);

                        // Subsequent flushes with upsert/delete
                        for (int f = 1; f < numFlushes; f++) {
                            index.flush(keysPerFlush / 2, upsertPct, deletePct);
                        }

                        totalEstimated += index.estimateCardinality();
                        totalActual += index.getActualLiveCount();
                    }

                    double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;
                    System.out.printf("%-8d %-10d %-10d %-15d %-15d %-12.2f%n", n, upsertPct, deletePct, totalActual,
                            totalEstimated, errorRate);
                }
            }
        }

        System.out.println();
    }

    // ========================================================================
    // Test: Stress Test - Large Scale Simulation
    // ========================================================================

    @Test
    public void testLargeScaleSimulation() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Large Scale LSM Simulation");
        System.out.println("=".repeat(80));
        System.out.println("Configuration: 32 indexes, 50,000 keys each, 10 flushes, mixed workload");
        System.out.println();

        int numIndexes = 32;
        int keysPerIndex = 50000;
        int numFlushes = 10;
        int keysPerFlush = keysPerIndex / numFlushes;

        long totalEstimated = 0;
        int totalActual = 0;
        int totalComponents = 0;

        long startTime = System.currentTimeMillis();

        for (int i = 0; i < numIndexes; i++) {
            int rangeStart = i * keysPerIndex * 2;
            int rangeEnd = rangeStart + keysPerIndex * 2 - 1;
            LSMIndex index = new LSMIndex(i, rangeStart, rangeEnd);

            // Simulate realistic workload
            // Flush 1: Initial bulk load
            index.flush(keysPerFlush * 2, 0, 0);

            // Flushes 2-5: Heavy inserts with some updates
            for (int f = 1; f < 5; f++) {
                index.flush(keysPerFlush, 20, 5);
            }

            // Flushes 6-8: More updates, moderate deletes
            for (int f = 5; f < 8; f++) {
                index.flush(keysPerFlush / 2, 40, 10);
            }

            // Flushes 9-10: Cleanup phase - more deletes
            for (int f = 8; f < numFlushes; f++) {
                index.flush(keysPerFlush / 4, 30, 20);
            }

            totalEstimated += index.estimateCardinality();
            totalActual += index.getActualLiveCount();
            totalComponents += index.getComponentCount();
        }

        long endTime = System.currentTimeMillis();

        double errorRate = Math.abs(totalEstimated - totalActual) / (double) totalActual * 100;

        System.out.println("Results:");
        System.out.println("-".repeat(40));
        System.out.printf("Total Indexes:      %d%n", numIndexes);
        System.out.printf("Total Components:   %d%n", totalComponents);
        System.out.printf("Expected Keys:      %,d%n", totalActual);
        System.out.printf("Estimated Keys:     %,d%n", totalEstimated);
        System.out.printf("Error Rate:         %.2f%%%n", errorRate);
        System.out.printf("Time Elapsed:       %d ms%n", endTime - startTime);
        System.out.println();

        // Assert reasonable accuracy
        assertTrue("Error rate should be within 25%, was " + errorRate + "%", errorRate <= 25);
    }

    // ========================================================================
    // Test: Accuracy Bounds Verification
    // ========================================================================

    @Test
    public void testAccuracyBounds() throws IOException {
        System.out.println("=".repeat(80));
        System.out.println("TEST: Accuracy Bounds Verification");
        System.out.println("=".repeat(80));
        System.out.println("Verifying error rates stay within expected bounds for various configurations");
        System.out.println();

        // Test 1: Simple case - should be < 10% error
        {
            LSMIndex index = new LSMIndex(0, 0, 100000);
            index.flush(10000, 0, 0);
            index.flush(10000, 0, 0);
            index.flush(10000, 0, 0);

            long estimated = index.estimateCardinality();
            int actual = index.getActualLiveCount();
            double errorRate = Math.abs(estimated - actual) / (double) actual * 100;

            System.out.printf("Simple 3-flush, no overlap: Expected=%d, Estimated=%d, Error=%.2f%%%n", actual,
                    estimated, errorRate);
            assertTrue("Simple case should have < 15% error", errorRate < 15);
        }

        // Test 2: Moderate upsert - should be < 15% error
        {
            LSMIndex index = new LSMIndex(0, 0, 100000);
            index.flush(10000, 0, 0);
            index.flush(5000, 30, 0);
            index.flush(5000, 30, 0);

            long estimated = index.estimateCardinality();
            int actual = index.getActualLiveCount();
            double errorRate = Math.abs(estimated - actual) / (double) actual * 100;

            System.out.printf("30%% upsert scenario: Expected=%d, Estimated=%d, Error=%.2f%%%n", actual, estimated,
                    errorRate);
            assertTrue("Moderate upsert should have < 20% error", errorRate < 20);
        }

        // Test 3: With deletes - should be < 20% error
        {
            LSMIndex index = new LSMIndex(0, 0, 100000);
            index.flush(15000, 0, 0);
            index.flush(5000, 20, 15);
            index.flush(5000, 20, 15);

            long estimated = index.estimateCardinality();
            int actual = index.getActualLiveCount();
            double errorRate = Math.abs(estimated - actual) / (double) actual * 100;

            System.out.printf("With deletes scenario: Expected=%d, Estimated=%d, Error=%.2f%%%n", actual, estimated,
                    errorRate);
            assertTrue("Delete scenario should have < 25% error", errorRate < 25);
        }

        System.out.println();
        System.out.println("All accuracy bounds verified successfully!");
    }
}
