/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * Generated by AI in Cursor IDE
 * Model: Claude Opus 4
 */
package org.apache.hyracks.storage.am.lsm.btree;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

import org.apache.hyracks.data.std.util.ArrayBackedValueStorage;
import org.apache.hyracks.dataflow.common.data.accessors.ITupleReference;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaEstimator;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaEstimator.ComponentStats;
import org.apache.hyracks.storage.am.lsm.common.theta.ThetaSampler;
import org.junit.Test;

/**
 * Comprehensive tests for ThetaSampler and ThetaEstimator.
 *
 * Tests cover:
 * - Basic sampling functionality
 * - Serialization/deserialization roundtrip
 * - Single component cardinality estimation
 * - Multi-component cardinality estimation with LSM semantics
 * - Delete (antimatter) handling
 * - Accuracy bounds verification
 * - Edge cases (empty, single tuple, duplicates)
 */
public class ThetaSketchTest {

    private static final double ACCEPTABLE_ERROR_RATE = 0.10; // 10% error tolerance

    // ========================================================================
    // Mock Tuple Implementation for Testing
    // ========================================================================

    /**
     * Simple mock tuple for testing ThetaSampler without full Hyracks infrastructure.
     */
    private static class MockTuple implements ITupleReference {
        private final byte[][] fields;

        public MockTuple(int... values) {
            this.fields = new byte[values.length][];
            for (int i = 0; i < values.length; i++) {
                fields[i] = intToBytes(values[i]);
            }
        }

        private static byte[] intToBytes(int value) {
            return new byte[] { (byte) (value >> 24), (byte) (value >> 16), (byte) (value >> 8), (byte) value };
        }

        @Override
        public int getFieldCount() {
            return fields.length;
        }

        @Override
        public byte[] getFieldData(int fIdx) {
            return fields[fIdx];
        }

        @Override
        public int getFieldStart(int fIdx) {
            return 0;
        }

        @Override
        public int getFieldLength(int fIdx) {
            return fields[fIdx].length;
        }
    }

    /**
     * Mock antimatter tuple for testing delete handling.
     */
    private static class MockAntimatterTuple extends MockTuple
            implements org.apache.hyracks.storage.am.lsm.common.api.ILSMTreeTupleReference {
        public MockAntimatterTuple(int... values) {
            super(values);
        }

        @Override
        public boolean isAntimatter() {
            return true;
        }

        @Override
        public int getTupleSize() {
            int size = 0;
            for (int i = 0; i < getFieldCount(); i++) {
                size += getFieldLength(i);
            }
            return size;
        }

        @Override
        public void setFieldCount(int fieldCount) {
            // No-op for mock
        }

        @Override
        public void setFieldCount(int fieldStartIndex, int fieldCount) {
            // No-op for mock
        }

        @Override
        public void resetByTupleOffset(byte[] buf, int tupleStartOffset) {
            // No-op for mock
        }

        @Override
        public void resetByTupleIndex(org.apache.hyracks.storage.am.common.api.ITreeIndexFrame frame, int tupleIndex) {
            // No-op for mock
        }
    }

    // ========================================================================
    // Basic ThetaSampler Tests
    // ========================================================================

    @Test
    public void testBasicSamplerCreation() {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);
        assertNotNull(sampler);
    }

    @Test
    public void testSamplerWithSingleTuple() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        sampler.addTuple(new MockTuple(42));

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        assertNotNull(stats);
        assertEquals(1, stats.insertSamples.length);
        assertEquals(0, stats.deleteSamples.length);
    }

    @Test
    public void testSamplerWithMultipleTuples() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        for (int i = 0; i < 100; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        assertNotNull(stats);
        assertEquals(100, stats.insertSamples.length);
        assertEquals(0, stats.deleteSamples.length);
    }

    @Test
    public void testSamplerWithMultiFieldKey() throws IOException {
        int[] keyFields = { 0, 1 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        for (int i = 0; i < 50; i++) {
            sampler.addTuple(new MockTuple(i, i * 2));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        assertNotNull(stats);
        assertEquals(50, stats.insertSamples.length);
    }

    // ========================================================================
    // Serialization/Deserialization Tests
    // ========================================================================

    @Test
    public void testSerializationRoundtrip() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        // Add enough tuples to fill the K samples
        for (int i = 0; i < 2000; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        // Should be capped at K (1024)
        assertEquals(1024, stats.insertSamples.length);
        assertEquals(1024, stats.K);

        // Samples should be sorted ascending
        for (int i = 1; i < stats.insertSamples.length; i++) {
            assertTrue("Samples should be sorted", stats.insertSamples[i - 1] <= stats.insertSamples[i]);
        }
    }

    @Test
    public void testSerializationWithDeletes() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        // Add inserts
        for (int i = 0; i < 500; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        // Add deletes (antimatter)
        for (int i = 500; i < 700; i++) {
            sampler.addTuple(new MockAntimatterTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        assertEquals(500, stats.insertSamples.length);
        assertEquals(200, stats.deleteSamples.length);
    }

    // ========================================================================
    // ComponentStats.getTheta() Tests
    // ========================================================================

    @Test
    public void testThetaWithFewSamples() {
        // When samples < K, theta should be 1.0
        long[] insertSamples = { 100L, 200L, 300L };
        long[] deleteSamples = {};
        ComponentStats stats = new ComponentStats(insertSamples, deleteSamples, 1024);

        assertEquals(1.0, stats.getTheta(), 0.0001);
    }

    @Test
    public void testThetaWithFullSamples() {
        // Create K samples
        long[] insertSamples = new long[1024];
        for (int i = 0; i < 1024; i++) {
            insertSamples[i] = (long) i * 1000000L;
        }
        long[] deleteSamples = {};
        ComponentStats stats = new ComponentStats(insertSamples, deleteSamples, 1024);

        double theta = stats.getTheta();
        assertTrue("Theta should be between 0 and 1", theta > 0 && theta <= 1.0);
        // Theta = largest sample / MAX_VALUE
        double expectedTheta = (double) insertSamples[1023] / (double) Long.MAX_VALUE;
        assertEquals(expectedTheta, theta, 0.0001);
    }

    // ========================================================================
    // ComponentStats.estimateLiveCardinality() Tests
    // ========================================================================

    @Test
    public void testEstimateLiveCardinalityNoDeletes() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        int actualCardinality = 5000;
        for (int i = 0; i < actualCardinality; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        long estimated = stats.estimateLiveCardinality();
        double errorRate = Math.abs(estimated - actualCardinality) / (double) actualCardinality;

        System.out.println("testEstimateLiveCardinalityNoDeletes - Expected: " + actualCardinality + ", Estimated: "
                + estimated + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    @Test
    public void testEstimateLiveCardinalityWithDeletes() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        // Insert 5000 tuples
        int insertCount = 5000;
        for (int i = 0; i < insertCount; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        // Delete 1000 of them (keys 0-999)
        int deleteCount = 1000;
        for (int i = 0; i < deleteCount; i++) {
            sampler.addTuple(new MockAntimatterTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        long estimated = stats.estimateLiveCardinality();
        int expectedLive = insertCount - deleteCount; // 4000

        double errorRate = Math.abs(estimated - expectedLive) / (double) expectedLive;

        System.out.println("testEstimateLiveCardinalityWithDeletes - Expected: " + expectedLive + ", Estimated: "
                + estimated + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    // ========================================================================
    // ThetaEstimator.estimateCardinality() - Single Component
    // ========================================================================

    @Test
    public void testEstimatorSingleComponent() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        int actualCardinality = 10000;
        for (int i = 0; i < actualCardinality; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        List<ComponentStats> components = new ArrayList<>();
        components.add(stats);

        long estimated = ThetaEstimator.estimateCardinality(components);
        double errorRate = Math.abs(estimated - actualCardinality) / (double) actualCardinality;

        System.out.println("testEstimatorSingleComponent - Expected: " + actualCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    @Test
    public void testEstimatorEmptyComponents() {
        List<ComponentStats> components = new ArrayList<>();
        long estimated = ThetaEstimator.estimateCardinality(components);
        assertEquals(0, estimated);
    }

    // ========================================================================
    // ThetaEstimator.estimateCardinality() - Multi-Component LSM Semantics
    // ========================================================================

    @Test
    public void testEstimatorMultiComponentNoOverlap() throws IOException {
        // Two components with no overlapping keys
        int[] keyFields = { 0 };

        // Component 1 (newer): keys 0-4999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 5000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        // Component 2 (older): keys 5000-9999
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 5000; i < 10000; i++) {
            sampler2.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());

        List<ComponentStats> components = Arrays.asList(ThetaSampler.deserialize(s1), ThetaSampler.deserialize(s2));

        long estimated = ThetaEstimator.estimateCardinality(components);
        int expectedCardinality = 10000;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;

        System.out.println("testEstimatorMultiComponentNoOverlap - Expected: " + expectedCardinality + ", Estimated: "
                + estimated + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    @Test
    public void testEstimatorMultiComponentWithOverlap() throws IOException {
        // Two components with overlapping keys - LSM semantics: newer wins
        int[] keyFields = { 0 };

        // Component 1 (newer): keys 0-4999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 5000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        // Component 2 (older): keys 2500-7499 (overlaps 2500-4999)
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 2500; i < 7500; i++) {
            sampler2.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());

        // Order: newest to oldest
        List<ComponentStats> components = Arrays.asList(ThetaSampler.deserialize(s1), ThetaSampler.deserialize(s2));

        long estimated = ThetaEstimator.estimateCardinality(components);
        // Unique keys: 0-7499 = 7500 distinct keys
        int expectedCardinality = 7500;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;

        System.out.println("testEstimatorMultiComponentWithOverlap - Expected: " + expectedCardinality + ", Estimated: "
                + estimated + ", Error: " + (errorRate * 100) + "%");

        // Allow higher error for multi-component estimation
        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    @Test
    public void testEstimatorWithDeletesAcrossComponents() throws IOException {
        // Newer component deletes keys from older component
        int[] keyFields = { 0 };

        // Component 1 (newer): deletes keys 0-999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 1000; i++) {
            sampler1.addTuple(new MockAntimatterTuple(i));
        }
        // Also insert some new keys
        for (int i = 10000; i < 12000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        // Component 2 (older): keys 0-4999
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 0; i < 5000; i++) {
            sampler2.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());

        // Order: newest to oldest
        List<ComponentStats> components = Arrays.asList(ThetaSampler.deserialize(s1), ThetaSampler.deserialize(s2));

        long estimated = ThetaEstimator.estimateCardinality(components);
        // Component 2: 0-4999 (5000 keys)
        // Component 1: deletes 0-999 (1000 keys), adds 10000-11999 (2000 keys)
        // Live keys: 1000-4999 (4000) + 10000-11999 (2000) = 6000
        int expectedCardinality = 6000;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;

        System.out.println("testEstimatorWithDeletesAcrossComponents - Expected: " + expectedCardinality
                + ", Estimated: " + estimated + ", Error: " + (errorRate * 100) + "%");

        // Allow higher error for complex multi-component estimation
        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    // ========================================================================
    // Edge Cases
    // ========================================================================

    @Test
    public void testEmptySampler() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        assertEquals(0, stats.insertSamples.length);
        assertEquals(0, stats.deleteSamples.length);
        assertEquals(1.0, stats.getTheta(), 0.0001);
        assertEquals(0, stats.estimateLiveCardinality());
    }

    @Test
    public void testDuplicateKeys() throws IOException {
        // NOTE: The optimized ThetaSampler STRICTLY deduplicates keys.
        // It maintains the true K-Minimum Values invariant by using an internal
        // hash set to reject duplicate hashes before they enter the heap.
        //
        // When inserting the same key N times:
        // - Only 1 hash is stored in the heap
        // - theta = 1.0 (since 1 < K)
        // - estimate = 1 / 1.0 = 1 (distinct count)
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        int insertCount = 1000;
        // Insert same key multiple times
        for (int i = 0; i < insertCount; i++) {
            sampler.addTuple(new MockTuple(42));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        // The sampler strictly rejects duplicates, so only 1 sample should be retained
        assertEquals("Only 1 unique hash should be retained in the sketch", 1, stats.insertSamples.length);

        // Since 1 < K, theta = 1.0
        assertEquals("Theta should be 1.0 when unique samples < K", 1.0, stats.getTheta(), 0.0001);

        // Estimate equals the distinct key count, which is exactly 1
        long estimated = stats.estimateLiveCardinality();
        assertEquals("Estimate should correctly reflect distinct cardinality (1)", 1, estimated);
    }

    @Test
    public void testLargeCardinality() throws IOException {
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        int actualCardinality = 100000;
        for (int i = 0; i < actualCardinality; i++) {
            sampler.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        long estimated = stats.estimateLiveCardinality();
        double errorRate = Math.abs(estimated - actualCardinality) / (double) actualCardinality;

        System.out.println("testLargeCardinality - Expected: " + actualCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    @Test
    public void testRandomDistribution() throws IOException {
        // Test with unique random keys (no duplicates) to verify accuracy
        // Note: ThetaSampler allows duplicates in the heap, which can reduce accuracy
        // when the same key is inserted multiple times. In real LSM usage, each key
        // is typically inserted once per flush, so we test with unique keys.
        int[] keyFields = { 0 };
        ThetaSampler sampler = new ThetaSampler(keyFields);

        Random rnd = new Random(12345);
        Set<Integer> uniqueKeys = new HashSet<>();
        int targetCardinality = 30000;

        // Generate unique random keys
        while (uniqueKeys.size() < targetCardinality) {
            uniqueKeys.add(rnd.nextInt(1000000));
        }

        // Insert only unique keys
        for (int key : uniqueKeys) {
            sampler.addTuple(new MockTuple(key));
        }

        ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
        serialized.append(sampler.serialize());
        ComponentStats stats = ThetaSampler.deserialize(serialized);

        long estimated = stats.estimateLiveCardinality();
        int actualCardinality = uniqueKeys.size();

        double errorRate = Math.abs(estimated - actualCardinality) / (double) actualCardinality;

        System.out.println("testRandomDistribution - Expected: " + actualCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    // ========================================================================
    // Three Component Test (Full LSM Simulation)
    // ========================================================================

    @Test
    public void testThreeComponentLSMSimulation() throws IOException {
        int[] keyFields = { 0 };

        // Component 3 (oldest): Initial data load - keys 0-9999
        ThetaSampler sampler3 = new ThetaSampler(keyFields);
        for (int i = 0; i < 10000; i++) {
            sampler3.addTuple(new MockTuple(i));
        }

        // Component 2 (middle): Some updates and new inserts
        // Updates keys 0-999 (same keys, newer version)
        // New keys 10000-11999
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 0; i < 1000; i++) {
            sampler2.addTuple(new MockTuple(i)); // updates
        }
        for (int i = 10000; i < 12000; i++) {
            sampler2.addTuple(new MockTuple(i)); // new
        }

        // Component 1 (newest): Deletes some keys
        // Deletes keys 5000-5999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 5000; i < 6000; i++) {
            sampler1.addTuple(new MockAntimatterTuple(i));
        }
        // Also adds keys 12000-12999
        for (int i = 12000; i < 13000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());
        ArrayBackedValueStorage s3 = new ArrayBackedValueStorage();
        s3.append(sampler3.serialize());

        // Order: newest to oldest
        List<ComponentStats> components =
                Arrays.asList(ThetaSampler.deserialize(s1), ThetaSampler.deserialize(s2), ThetaSampler.deserialize(s3));

        long estimated = ThetaEstimator.estimateCardinality(components);

        // Expected live keys:
        // From C3: 0-9999 (10000) but:
        //   - 0-999 are "superseded" by C2 (same key, newer version - still alive)
        //   - 5000-5999 are deleted by C1
        // From C2: 10000-11999 (2000 new keys)
        // From C1: 12000-12999 (1000 new keys)
        //
        // Unique live keys: 0-4999 (5000) + 6000-9999 (4000) + 10000-12999 (3000) = 12000
        // Wait, the LSM semantics in the code:
        // - seenKeys tracks all keys we've processed
        // - aliveKeys only adds if not in seenKeys
        // So C1's deletes go to seenKeys, C1's inserts go to aliveKeys
        // C2's keys: if in seenKeys (from C1 deletes), skip; else add to aliveKeys
        // C3's keys: if in seenKeys (from C1+C2), skip; else add to aliveKeys
        //
        // Actually: C1 inserts 12000-12999, deletes 5000-5999
        // C2 inserts 0-999, 10000-11999
        // C3 inserts 0-9999
        //
        // Processing newest to oldest:
        // C1: alive += 12000-12999 (1000), seen += 12000-12999 + 5000-5999 (2000 total)
        // C2: alive += 0-999 (not in seen), 10000-11999 (not in seen) => +3000
        //     seen += 0-999, 10000-11999
        // C3: alive += 1000-4999 (not in seen, 4000), 6000-9999 (not in seen, 4000) => +8000
        //     (0-999 in seen, 5000-5999 in seen)
        //
        // Total alive = 1000 + 3000 + 8000 = 12000
        int expectedCardinality = 12000;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;

        System.out.println("testThreeComponentLSMSimulation - Expected: " + expectedCardinality + ", Estimated: "
                + estimated + ", Error: " + (errorRate * 100) + "%");

        // Allow higher error for complex multi-component estimation
        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    // ========================================================================
    // Accuracy Consistency Test
    // ========================================================================

    @Test
    public void testAccuracyConsistency() throws IOException {
        // Run multiple trials and verify consistent accuracy
        int[] keyFields = { 0 };
        int numTrials = 5;
        int cardinality = 20000;
        double totalError = 0;

        System.out.println(
                "testAccuracyConsistency - Running " + numTrials + " trials with " + cardinality + " keys each:");

        for (int trial = 0; trial < numTrials; trial++) {
            ThetaSampler sampler = new ThetaSampler(keyFields);
            // Use different base to get different hash values each trial
            int base = trial * 100000;
            for (int i = 0; i < cardinality; i++) {
                sampler.addTuple(new MockTuple(base + i));
            }

            ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
            serialized.append(sampler.serialize());
            ComponentStats stats = ThetaSampler.deserialize(serialized);

            long estimated = stats.estimateLiveCardinality();
            double errorRate = Math.abs(estimated - cardinality) / (double) cardinality;
            totalError += errorRate;

            System.out.println("  Trial " + (trial + 1) + " - Expected: " + cardinality + ", Estimated: " + estimated
                    + ", Error: " + (errorRate * 100) + "%");
        }

        double avgError = totalError / numTrials;

        System.out.println("  Average Error: " + (avgError * 100) + "%");

        assertTrue("Average error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (avgError * 100)
                + "%", avgError <= ACCEPTABLE_ERROR_RATE);
    }

    // ========================================================================
    // LSM Disk Component Simulation Tests
    // ========================================================================
    // These tests simulate realistic LSM flush scenarios where:
    // - Each flush creates a new disk component with a ThetaSampler
    // - Keys within a single component are unique (one key per tuple in a flush)
    // - Newer components may contain keys that also exist in older components (updates)
    // - ThetaEstimator combines all component stats to estimate live cardinality

    /**
     * Simulates 5 sequential LSM flushes with no key overlap.
     * Each flush adds new unique keys to the index.
     */
    @Test
    public void testLSMSimulation_FiveFlushesNoOverlap() throws IOException {
        int[] keyFields = { 0 };
        int keysPerFlush = 5000;
        int numFlushes = 5;

        List<ComponentStats> components = new ArrayList<>();
        Set<Integer> allKeys = new HashSet<>();

        // Simulate 5 flushes, each adding unique keys
        for (int flush = 0; flush < numFlushes; flush++) {
            ThetaSampler sampler = new ThetaSampler(keyFields);
            int baseKey = flush * keysPerFlush;

            for (int i = 0; i < keysPerFlush; i++) {
                int key = baseKey + i;
                allKeys.add(key);
                sampler.addTuple(new MockTuple(key));
            }

            ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
            serialized.append(sampler.serialize());
            // Add to front (newest first)
            components.add(0, ThetaSampler.deserialize(serialized));
        }

        long estimated = ThetaEstimator.estimateCardinality(components);
        int expectedCardinality = allKeys.size(); // 25000

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM 5 Flushes No Overlap - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 100) + "%, was " + (errorRate * 100) + "%",
                errorRate <= ACCEPTABLE_ERROR_RATE);
    }

    /**
     * Simulates LSM flushes where newer flushes update some keys from older flushes.
     * This is the most common LSM pattern - updates to existing records.
     */
    @Test
    public void testLSMSimulation_FlushesWithUpdates() throws IOException {
        int[] keyFields = { 0 };

        List<ComponentStats> components = new ArrayList<>();
        Set<Integer> liveKeys = new HashSet<>();

        // Flush 1 (oldest): Insert keys 0-9999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 10000; i++) {
            sampler1.addTuple(new MockTuple(i));
            liveKeys.add(i);
        }

        // Flush 2: Update keys 0-2999 (existing) + Insert 10000-12999 (new)
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 0; i < 3000; i++) {
            sampler2.addTuple(new MockTuple(i)); // updates
        }
        for (int i = 10000; i < 13000; i++) {
            sampler2.addTuple(new MockTuple(i)); // new keys
            liveKeys.add(i);
        }

        // Flush 3 (newest): Update keys 5000-5999 + Insert 13000-14999
        ThetaSampler sampler3 = new ThetaSampler(keyFields);
        for (int i = 5000; i < 6000; i++) {
            sampler3.addTuple(new MockTuple(i)); // updates
        }
        for (int i = 13000; i < 15000; i++) {
            sampler3.addTuple(new MockTuple(i)); // new keys
            liveKeys.add(i);
        }

        // Serialize all samplers
        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());
        ArrayBackedValueStorage s3 = new ArrayBackedValueStorage();
        s3.append(sampler3.serialize());

        // Order: newest to oldest
        components.add(ThetaSampler.deserialize(s3));
        components.add(ThetaSampler.deserialize(s2));
        components.add(ThetaSampler.deserialize(s1));

        long estimated = ThetaEstimator.estimateCardinality(components);
        int expectedCardinality = liveKeys.size(); // 15000 unique keys

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM Flushes With Updates - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    /**
     * Simulates LSM with deletes - newer components contain antimatter tuples
     * that logically delete keys from older components.
     */
    @Test
    public void testLSMSimulation_FlushesWithDeletes() throws IOException {
        int[] keyFields = { 0 };

        List<ComponentStats> components = new ArrayList<>();

        // Flush 1 (oldest): Insert keys 0-19999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 20000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        // Flush 2: Delete keys 0-4999 + Insert 20000-24999
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 0; i < 5000; i++) {
            sampler2.addTuple(new MockAntimatterTuple(i)); // deletes
        }
        for (int i = 20000; i < 25000; i++) {
            sampler2.addTuple(new MockTuple(i)); // new keys
        }

        // Flush 3 (newest): Delete keys 10000-11999 + Insert 25000-26999
        ThetaSampler sampler3 = new ThetaSampler(keyFields);
        for (int i = 10000; i < 12000; i++) {
            sampler3.addTuple(new MockAntimatterTuple(i)); // deletes
        }
        for (int i = 25000; i < 27000; i++) {
            sampler3.addTuple(new MockTuple(i)); // new keys
        }

        // Serialize all samplers
        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());
        ArrayBackedValueStorage s3 = new ArrayBackedValueStorage();
        s3.append(sampler3.serialize());

        // Order: newest to oldest
        components.add(ThetaSampler.deserialize(s3));
        components.add(ThetaSampler.deserialize(s2));
        components.add(ThetaSampler.deserialize(s1));

        long estimated = ThetaEstimator.estimateCardinality(components);

        // Expected live keys:
        // From C1: 0-19999 (20000) minus deleted (0-4999 by C2, 10000-11999 by C3)
        //   = 5000-9999 (5000) + 12000-19999 (8000) = 13000
        // From C2: 20000-24999 (5000)
        // From C3: 25000-26999 (2000)
        // Total: 13000 + 5000 + 2000 = 20000
        int expectedCardinality = 20000;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM Flushes With Deletes - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    /**
     * Simulates a realistic workload: initial bulk load followed by
     * incremental updates and some deletes over multiple flushes.
     */
    @Test
    public void testLSMSimulation_RealisticWorkload() throws IOException {
        int[] keyFields = { 0 };
        Random rnd = new Random(42);

        List<ComponentStats> components = new ArrayList<>();
        Set<Integer> liveKeys = new HashSet<>();

        // Flush 1 (oldest): Bulk load of 50000 keys
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 50000; i++) {
            sampler1.addTuple(new MockTuple(i));
            liveKeys.add(i);
        }

        // Flush 2: 10% updates (5000 random existing keys) + 5000 new keys
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        Set<Integer> updatedKeys = new HashSet<>();
        while (updatedKeys.size() < 5000) {
            updatedKeys.add(rnd.nextInt(50000));
        }
        for (int key : updatedKeys) {
            sampler2.addTuple(new MockTuple(key));
        }
        for (int i = 50000; i < 55000; i++) {
            sampler2.addTuple(new MockTuple(i));
            liveKeys.add(i);
        }

        // Flush 3: 2% deletes (1000 random keys) + 3000 new keys
        ThetaSampler sampler3 = new ThetaSampler(keyFields);
        Set<Integer> deletedKeys = new HashSet<>();
        while (deletedKeys.size() < 1000) {
            int key = rnd.nextInt(55000);
            if (liveKeys.contains(key)) {
                deletedKeys.add(key);
            }
        }
        for (int key : deletedKeys) {
            sampler3.addTuple(new MockAntimatterTuple(key));
            liveKeys.remove(key);
        }
        for (int i = 55000; i < 58000; i++) {
            sampler3.addTuple(new MockTuple(i));
            liveKeys.add(i);
        }

        // Flush 4 (newest): More updates and new keys
        ThetaSampler sampler4 = new ThetaSampler(keyFields);
        Set<Integer> updatedKeys2 = new HashSet<>();
        while (updatedKeys2.size() < 2000) {
            int key = rnd.nextInt(58000);
            if (liveKeys.contains(key)) {
                updatedKeys2.add(key);
            }
        }
        for (int key : updatedKeys2) {
            sampler4.addTuple(new MockTuple(key));
        }
        for (int i = 58000; i < 60000; i++) {
            sampler4.addTuple(new MockTuple(i));
            liveKeys.add(i);
        }

        // Serialize all samplers
        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());
        ArrayBackedValueStorage s3 = new ArrayBackedValueStorage();
        s3.append(sampler3.serialize());
        ArrayBackedValueStorage s4 = new ArrayBackedValueStorage();
        s4.append(sampler4.serialize());

        // Order: newest to oldest
        components.add(ThetaSampler.deserialize(s4));
        components.add(ThetaSampler.deserialize(s3));
        components.add(ThetaSampler.deserialize(s2));
        components.add(ThetaSampler.deserialize(s1));

        long estimated = ThetaEstimator.estimateCardinality(components);
        int expectedCardinality = liveKeys.size();

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM Realistic Workload - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    /**
     * Simulates many small flushes - typical of write-heavy OLTP workload.
     */
    @Test
    public void testLSMSimulation_ManySmallFlushes() throws IOException {
        int[] keyFields = { 0 };
        int numFlushes = 20;
        int keysPerFlush = 2000;

        List<ComponentStats> components = new ArrayList<>();
        Set<Integer> allKeys = new HashSet<>();
        int nextKey = 0;

        for (int flush = 0; flush < numFlushes; flush++) {
            ThetaSampler sampler = new ThetaSampler(keyFields);

            for (int i = 0; i < keysPerFlush; i++) {
                int key = nextKey++;
                allKeys.add(key);
                sampler.addTuple(new MockTuple(key));
            }

            ArrayBackedValueStorage serialized = new ArrayBackedValueStorage();
            serialized.append(sampler.serialize());
            // Add to front (newest first)
            components.add(0, ThetaSampler.deserialize(serialized));
        }

        long estimated = ThetaEstimator.estimateCardinality(components);
        int expectedCardinality = allKeys.size(); // 40000

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM Many Small Flushes - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }

    /**
     * Simulates high-overlap scenario where newer components heavily update older ones.
     * This is common in indexes with hot keys that are frequently updated.
     */
    @Test
    public void testLSMSimulation_HighOverlapUpdates() throws IOException {
        int[] keyFields = { 0 };

        List<ComponentStats> components = new ArrayList<>();

        // Flush 1 (oldest): Insert keys 0-9999
        ThetaSampler sampler1 = new ThetaSampler(keyFields);
        for (int i = 0; i < 10000; i++) {
            sampler1.addTuple(new MockTuple(i));
        }

        // Flush 2: Update 80% of keys (0-7999) + 2000 new keys
        ThetaSampler sampler2 = new ThetaSampler(keyFields);
        for (int i = 0; i < 8000; i++) {
            sampler2.addTuple(new MockTuple(i));
        }
        for (int i = 10000; i < 12000; i++) {
            sampler2.addTuple(new MockTuple(i));
        }

        // Flush 3: Update another 80% (0-7999 again) + 2000 new keys
        ThetaSampler sampler3 = new ThetaSampler(keyFields);
        for (int i = 0; i < 8000; i++) {
            sampler3.addTuple(new MockTuple(i));
        }
        for (int i = 12000; i < 14000; i++) {
            sampler3.addTuple(new MockTuple(i));
        }

        // Flush 4 (newest): Update 50% (0-4999) + 1000 new keys
        ThetaSampler sampler4 = new ThetaSampler(keyFields);
        for (int i = 0; i < 5000; i++) {
            sampler4.addTuple(new MockTuple(i));
        }
        for (int i = 14000; i < 15000; i++) {
            sampler4.addTuple(new MockTuple(i));
        }

        // Serialize all samplers
        ArrayBackedValueStorage s1 = new ArrayBackedValueStorage();
        s1.append(sampler1.serialize());
        ArrayBackedValueStorage s2 = new ArrayBackedValueStorage();
        s2.append(sampler2.serialize());
        ArrayBackedValueStorage s3 = new ArrayBackedValueStorage();
        s3.append(sampler3.serialize());
        ArrayBackedValueStorage s4 = new ArrayBackedValueStorage();
        s4.append(sampler4.serialize());

        // Order: newest to oldest
        components.add(ThetaSampler.deserialize(s4));
        components.add(ThetaSampler.deserialize(s3));
        components.add(ThetaSampler.deserialize(s2));
        components.add(ThetaSampler.deserialize(s1));

        long estimated = ThetaEstimator.estimateCardinality(components);

        // Expected: All unique keys = 0-14999 = 15000
        int expectedCardinality = 15000;

        double errorRate = Math.abs(estimated - expectedCardinality) / (double) expectedCardinality;
        System.out.println("LSM High Overlap Updates - Expected: " + expectedCardinality + ", Estimated: " + estimated
                + ", Error: " + (errorRate * 100) + "%");

        assertTrue("Error rate should be within " + (ACCEPTABLE_ERROR_RATE * 2 * 100) + "%, was " + (errorRate * 100)
                + "%", errorRate <= ACCEPTABLE_ERROR_RATE * 2);
    }
}
