#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

if [ -z $ASTERIX_HOME ]
 then
   pushd $(dirname $0) >/dev/null
   cd ..
   export ASTERIX_HOME=$(pwd)
   popd >/dev/null
fi

for jar in `ls $ASTERIX_HOME/lib/*.jar`
  do 
  if [ -z $ASTERIX_CLASSPATH ] 
  then 
    ASTERIX_CLASSPATH=$jar 
  else
    ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:$jar 
  fi
done

ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:
ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:$YARN_CONF_DIR:$HADOOP_CONF_DIR:$HADOOP_CONF_PATH
pushd $(dirname $0) > /dev/null
cd $ASTERIX_HOME
java $JAVA_OPTS -cp $ASTERIX_CLASSPATH -Dlog4j.configuration=file://$ASTERIX_HOME/conf/asterix-client-log4j.properties org.apache.asterix.aoya.AsterixYARNClient $@
popd > /dev/null
