#!/usr/bin/env bash
if [ -z $ASTERIX_HOME ]
 then
   pushd $(dirname $0) >/dev/null
   cd ..
   export ASTERIX_HOME=$(pwd)
   popd >/dev/null
fi

for jar in `ls $ASTERIX_HOME/lib/*.jar`
  do 
  if [ -z $ASTERIX_CLASSPATH ] 
  then 
    ASTERIX_CLASSPATH=$jar 
  else
    ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:$jar 
  fi
done

ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:
ASTERIX_CLASSPATH=$ASTERIX_CLASSPATH:$YARN_CONF_DIR:$HADOOP_CONF_DIR:$HADOOP_CONF_PATH
pushd $(dirname $0) > /dev/null
cd $ASTERIX_HOME
java $JAVA_OPTS -cp $ASTERIX_CLASSPATH -Dlog4j.configuration=file://$ASTERIX_HOME/conf/asterix-client-log4j.properties edu.uci.ics.asterix.aoya.AsterixYARNClient $@
popd > /dev/null
